blank_issues_enabled: false
contact_links:
  - name: 讨论区
    url: https://github.com/Lunova-Studio/WonderLab.Override/discussions
    about: 使用中若遇到问题或有新点子新需求，请先在这里求助和征求意见
  - name: 加入内测用户 QQ 群
    url: http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=DPckFEoH0xV4GNrrmgDyZLKMnB5WVwNE&authKey=tfhkyDv5sOSINzwpWhsmzM8IOpoxYaqO9FwHZaGcXjJIAvioBxlzEhl9CdmgB0i%2F&noverify=0&group_code=688942089
    about: 在 QQ 群和开发者以及其它用户交流讨论
